### ISSUE TITLE
Window Flickers and Disappears in 10.10.2

### ISSUE THREAD

**Issue by aaronjeline** [Nasga/iterm2-borderless#1]
Launching a new window just flickers and then vanishes.

**Comment by SebastienElet** [comment]
I have no issue with 10.10.3.

I only apply a tiny patch to remove border, do you have the same issue with official iterm2 ?

**Comment by aaronjeline** [comment]
Nope, not at all. I'll upgrade to 10.10.3 and see if it goes away. 

—

**Comment by SebastienElet** [comment]
No news, and the bug does not seems related to my patch.

I close.
