### ISSUE TITLE
Building after reset fails

### ISSUE THREAD

**Issue by atelic** [Nasga/iterm2-borderless#2]
## Steps
- Clone the iterm2-borderless repo
- Run `make build`
- Run `make reset`
- Try to build again with `make build`
## Expected behavior
- The application builds successfully like the first time `make build` was run
## Current behavior
- Make is unable to build again because iTerm2/bin/ exists and is trying to `mkdir iTerm2/bin`
  ![screen shot 2015-06-09 at 11 05 22 pm](https://cloud.githubusercontent.com/assets/8905795/8074123/15da97cc-0efc-11e5-8552-5512d46dd0fa.png)
- After removing iTerm2/bin and running `make build` again, install succeeds but exits with 1 because iTerm.app/iTerm2.app is not empty
  ![screen shot 2015-06-09 at 11 13 11 pm](https://cloud.githubusercontent.com/assets/8905795/8074213/242d1308-0efd-11e5-8a68-fc4fa292ec68.png)
## Possible solution

In the `Makefile`, checking if these directories exist and deleting them if they do should resolve the issue

**Comment by SebastienElet** [comment]
I know this issue, but thanks for this nice report.

The main issue is it's really crap to keep iTerm binary in the git repo.

I plan to use travis to build the binary and push it to gh-pages branch (this would also test / validate the makefile).

**Comment by atelic** [comment]
Closed per SHA: 5d2c7ee
